spring:
  application:
    name: coffehub

server:
  port: 9091

logging:
  file:
    path: /logs/application.log
    max-size: 10MB
    max-history: 30
  level:
    root:
      - error
      - debug
      - info
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] [%-5level] - %msg%n"


  logback:
    rolling-policy:
      file-name-pattern: /logs/%d{yyyy-MM-dd}/%d{yyyy-MM-dd'T'HH:mm:ss, aux}.%i.log

location-id: 1