spring:
  application:
    name: coffehub
  datasource:
    url: jdbc:mysql://127.0.0.1:9090/coffe_hub
    username: root
    password: Ksu12345!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9091

logging:
  file:
    path: /logs/application.log
    max-size: 10MB
    max-history: 30
  level:
    root:
      - error
      - debug
      - info
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] [%-5level] - %msg%n"


  logback:
    rolling-policy:
      file-name-pattern: /logs/%d{yyyy-MM-dd}/%d{yyyy-MM-dd'T'HH:mm:ss, aux}.%i.log

location-id: 1